name: build

on:
  workflow_dispatch:

run-name: Build

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install toolchain
      run: |
        sudo apt update
        sudo apt --fix-missing install gcc-aarch64-linux-gnu iasl device-tree-compiler python3-pyelftools
    - name: Build
      run: |
        make sdcard
    
